version: '2'
services:
  springbootapp:
    image: porichigo15/springbootapp:0.0.1
    container_name: springbootapp
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://productdb:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false
    ports:
      - 8080:8080

  mariadb:
    image: mariadb:latest
    container_name: productdb
    volumes:
      - /home/docker/volumes/myapp/H2/:/var/lib/H2/
    environment:
      - H2_USER=h2db
      - H2_PASSWORD=1234
